package yj.core.zudlog.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "wip_zudlog")
public class Zudlog extends BaseDTO {
     @Id
     @GeneratedValue
      private String id;

      private String zudnum;

      private String item;

      private String status; //处理成功 1 处理失败 2

      private Long inputlogid;

      private String msgtx;

    public String getMsgtx() {
        return msgtx;
    }

    public void setMsgtx(String msgtx) {
        this.msgtx = msgtx;
    }

    public Long getInputlogid() {
        return inputlogid;
    }

    public void setInputlogid(Long inputlogid) {
        this.inputlogid = inputlogid;
    }

    public void setId(String id){
         this.id = id;
     }

     public String getId(){
         return id;
     }

     public void setZudnum(String zudnum){
         this.zudnum = zudnum;
     }

     public String getZudnum(){
         return zudnum;
     }

     public void setItem(String item){
         this.item = item;
     }

     public String getItem(){
         return item;
     }

     public void setStatus(String status){
         this.status = status;
     }

     public String getStatus(){
         return status;
     }

     }
