package yj.core.wiplines.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
import javax.validation.constraints.NotNull;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "wip_lines")
public class Lines extends BaseDTO {
     @NotEmpty
      private String werks; //工厂

      private String deptId; //部门ID

     @Id
     @GeneratedValue
      private Long lineId; //产线ID

     @NotEmpty
      private String lineCode; //产线编码

     @NotEmpty
      private String descriptions; //产线描述

      private Long plineId; //父产线ID

      private String arbpl; //工作中心

      private String enableFlag; //是否启用

      private Date startDate; //生效日期

      private Date endDate; //失效日期

      private Long taktTime; //生产节拍

      @NotNull
      private String onlinetype;//上线类型 0：批次 1：二维码

      private String segOprName;//工序段名称

      private Long pointNum; //工序数量

      private Date creationDate; //创建时间

     @NotNull
      private Long createdBy; //创建人

      private Date lastUpdatedDate; //更新时间

      private Long lastUpdatedBy; //更新人


     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setDeptId(String deptId){
         this.deptId = deptId;
     }

     public String getDeptId(){
         return deptId;
     }

     public void setLineId(Long lineId){
         this.lineId = lineId;
     }

     public Long getLineId(){
         return lineId;
     }

     public void setLineCode(String lineCode){
         this.lineCode = lineCode;
     }

     public String getLineCode(){
         return lineCode;
     }

     public void setDescriptions(String descriptions){
         this.descriptions = descriptions;
     }

     public String getDescriptions(){
         return descriptions;
     }

     public void setPlineId(Long plineId){
         this.plineId = plineId;
     }

     public Long getPlineId(){
         return plineId;
     }

     public void setArbpl(String arbpl){
         this.arbpl = arbpl;
     }

     public String getArbpl(){
         return arbpl;
     }

     public void setEnableFlag(String enableFlag){
         this.enableFlag = enableFlag;
     }

     public String getEnableFlag(){
         return enableFlag;
     }

     public void setStartDate(Date startDate){
         this.startDate = startDate;
     }

     public Date getStartDate(){
         return startDate;
     }

     public void setEndDate(Date endDate){
         this.endDate = endDate;
     }

     public Date getEndDate(){
         return endDate;
     }

     public void setTaktTime(Long taktTime){
         this.taktTime = taktTime;
     }

     public Long getTaktTime(){
         return taktTime;
     }

     public void setPointNum(Long pointNum){
         this.pointNum = pointNum;
     }

     public Long getPointNum(){
         return pointNum;
     }

     public void setCreationDate(Date creationDate){
         this.creationDate = creationDate;
     }

     public Date getCreationDate(){
         return creationDate;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

     public void setLastUpdatedDate(Date lastUpdatedDate){
         this.lastUpdatedDate = lastUpdatedDate;
     }

     public Date getLastUpdatedDate(){
         return lastUpdatedDate;
     }

     public void setLastUpdatedBy(Long lastUpdatedBy){
         this.lastUpdatedBy = lastUpdatedBy;
     }

     public Long getLastUpdatedBy(){
         return lastUpdatedBy;
     }

    public String getSegOprName() {
        return segOprName;
    }

    public void setSegOprName(String segOprName) {
        this.segOprName = segOprName;
    }

    public String getOnlinetype() {
        return onlinetype;
    }

    public void setOnlinetype(String onlinetype) {
        this.onlinetype = onlinetype;
    }
}
