package yj.core.wipcggroupdes.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
@ExtensionAttribute(disable=true)
@Table(name = "wip_cggroup_des")
public class CggroupDes extends BaseDTO {
     @Id
     @GeneratedValue
      private String cggroup; //产线组编码

     @NotEmpty
      private String cggroupname; //产线组名称


     public void setCggroup(String cggroup){
         this.cggroup = cggroup;
     }

     public String getCggroup(){
         return cggroup;
     }

     public void setCggroupname(String cggroupname){
         this.cggroupname = cggroupname;
     }

     public String getCggroupname(){
         return cggroupname;
     }

     }
