package yj.core.webservice_readztpbar.sender;

import yj.core.webservice_readztpbar.receiver.DTREADZTPBAR2Res;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 *
 */
@WebService(name = "SI_READZTPBAR2_Sender_Syn", targetNamespace = "http://www.cq-yj.com/HAP/READZTPBAR2/Sender")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SIREADZTPBAR2SenderSyn {

    /**
     *
     * @param mtREADZTPBAR2Req
     * @return returns com.cq_yj.hap.readztpbar2.sender.DTREADZTPBAR2Res
     */
    @WebMethod(operationName = "SI_READZTPBAR2_Sender_Syn", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_READZTPBAR2_Res", targetNamespace = "http://www.cq-yj.com/HAP/READZTPBAR2/Sender", partName = "MT_READZTPBAR2_Res")
    public DTREADZTPBAR2Res siREADZTPBAR2SenderSyn(
            @WebParam(name = "MT_READZTPBAR2_Req", targetNamespace = "http://www.cq-yj.com/HAP/READZTPBAR2/Sender", partName = "MT_READZTPBAR2_Req") DTREADZTPBAR2Req mtREADZTPBAR2Req);

}