package yj.core.webservice_readztpbar.sender;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import java.net.URL;
import java.util.logging.Logger;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 *
 * <pre>
 * SI_READZTPBAR_Sender_SynService service = new SI_READZTPBAR_Sender_SynService();
 * SIREADZTPBAR2SenderSyn portType = service.getHTTPPort();
 * portType.siREADZTPBARSenderSyn(...);
 * </pre>
 *
 * </p>
 *
 */
@WebServiceClient(name = "SI_READZTPBAR2_Sender_SynService", targetNamespace = "http://www.cq-yj.com/HAP/READZTPBAR2/Sender", wsdlLocation = "resources/readztpbar2.xml")
public class SIREADZTPBAR2SenderSynService extends Service {

    public final static URL WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(SIREADZTPBAR2SenderSynService.class.getName());

    static {
        URL url = null;
        url = SIREADZTPBAR2SenderSynService.class.getClassLoader().getResource("readztpbar2.xml");
        System.out.println(url);
        WSDL_LOCATION = url;
    }

    public SIREADZTPBAR2SenderSynService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIREADZTPBAR2SenderSynService() {
        super(WSDL_LOCATION, new QName(
                "http://www.cq-yj.com/HAP/READZTPBAR2/Sender",
                "SI_READZTPBAR2_Sender_SynService"));
    }

    /**
     *
     * @return returns SIREADZTPBAR2SenderSyn
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIREADZTPBAR2SenderSyn getHTTPPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/READZTPBAR2/Sender", "HTTP_Port"),
                SIREADZTPBAR2SenderSyn.class);
    }

    /**
     *
     * @return returns SIREADZTPBAR2SenderSyn
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIREADZTPBAR2SenderSyn getHTTPSPort() {
        return super.getPort(new QName(
                        "http://www.cq-yj.com/HAP/READZTPBAR2/Sender", "HTTPS_Port"),
                SIREADZTPBAR2SenderSyn.class);
    }

}