package yj.core.dispath.dto;

/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "confirmation_log")
public class Log extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String tranType; //事物类型：报工/冲销

      private Long refId; //参考ID

      private String msgty; //消息类型

      private String msgtx; //消息内容

      private Long programId; //程序id

      private Long requestId; //请求id

      private Date creationDate; //创建日期

      private Long createdBy; //创建者

      private Date lastUpdateDate; //最近更新日期

      private Long lastUpdatedBy; //最近更新人


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTranType(String tranType){
         this.tranType = tranType;
     }

     public String getTranType(){
         return tranType;
     }

     public void setRefId(Long refId){
         this.refId = refId;
     }

     public Long getRefId(){
         return refId;
     }

     public void setMsgty(String msgty){
         this.msgty = msgty;
     }

     public String getMsgty(){
         return msgty;
     }

     public void setMsgtx(String msgtx){
         this.msgtx = msgtx;
     }

     public String getMsgtx(){
         return msgtx;
     }

     public void setProgramId(Long programId){
         this.programId = programId;
     }

     public Long getProgramId(){
         return programId;
     }

     public void setRequestId(Long requestId){
         this.requestId = requestId;
     }

     public Long getRequestId(){
         return requestId;
     }

     public void setCreationDate(Date creationDate){
         this.creationDate = creationDate;
     }

     public Date getCreationDate(){
         return creationDate;
     }

     public void setCreatedBy(Long createdBy){
         this.createdBy = createdBy;
     }

     public Long getCreatedBy(){
         return createdBy;
     }

     public void setLastUpdateDate(Date lastUpdateDate){
         this.lastUpdateDate = lastUpdateDate;
     }

     public Date getLastUpdateDate(){
         return lastUpdateDate;
     }

     public void setLastUpdatedBy(Long lastUpdatedBy){
         this.lastUpdatedBy = lastUpdatedBy;
     }

     public Long getLastUpdatedBy(){
         return lastUpdatedBy;
     }

     }
