package yj.core.dispatch.dto;


/**Auto Generated By Hap Code Generator**/

import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@ExtensionAttribute(disable=true)
@Table(name = "confirmation_log")
public class Log extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String tranType; //事物类型：报工/冲销

      private Long refId; //参考ID

      private String msgty; //消息类型

      private String msgtx; //消息内容




     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTranType(String tranType){
         this.tranType = tranType;
     }

     public String getTranType(){
         return tranType;
     }

     public void setRefId(Long refId){
         this.refId = refId;
     }

     public Long getRefId(){
         return refId;
     }

     public void setMsgty(String msgty){
         this.msgty = msgty;
     }

     public String getMsgty(){
         return msgty;
     }

     public void setMsgtx(String msgtx){
         this.msgtx = msgtx;
     }

     public String getMsgtx(){
         return msgtx;
     }



     }
