package yj.core.dispatch.dto;


/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "confirmation_test")
public class Test extends BaseDTO {
     @Id
     @GeneratedValue
      private Long id;

      private String testOne;

      private Long testTwo;

      private String testThree;

      private Date testFour;


     public void setId(Long id){
         this.id = id;
     }

     public Long getId(){
         return id;
     }

     public void setTestOne(String testOne){
         this.testOne = testOne;
     }

     public String getTestOne(){
         return testOne;
     }

     public void setTestTwo(Long testTwo){
         this.testTwo = testTwo;
     }

     public Long getTestTwo(){
         return testTwo;
     }

     public void setTestThree(String testThree){
         this.testThree = testThree;
     }

     public String getTestThree(){
         return testThree;
     }

     public void setTestFour(Date testFour){
         this.testFour = testFour;
     }

     public Date getTestFour(){
         return testFour;
     }

     }
