package yj.core.pandiantcode.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
@ExtensionAttribute(disable=true)
@Table(name = "wip_pandiantcode")
public class Pandiantcode extends BaseDTO {
     @Id
     @GeneratedValue
      private String username;

      private String tjpd;

      private String gzpd;


     public void setUsername(String username){
         this.username = username;
     }

     public String getUsername(){
         return username;
     }

     public void setTjpd(String tjpd){
         this.tjpd = tjpd;
     }

     public String getTjpd(){
         return tjpd;
     }

     public void setGzpd(String gzpd){
         this.gzpd = gzpd;
     }

     public String getGzpd(){
         return gzpd;
     }

     }
