package yj.core.wipcgroupplan.dto;

/**Auto Generated By Hap Code Generator**/
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;

import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import java.sql.Time;
import java.util.Date;

@ExtensionAttribute(disable=true)
@Table(name = "wip_cgroup_plan")
public class CgroupPlan extends BaseDTO {
     @Id
     @GeneratedValue
      private String werks; //工厂

      private Long deptId; //部门

     @NotEmpty
      private String cgroup; //产线组

      private Date plandate; //生产计划日期

      private Long planpos; //生产计划行

      private Time plantimestart; //计划开始时间

      private Time plantimeend; //计划结束时间

      private Double planqty; //计划产量

    private String remarks;//备注

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setDeptId(Long deptId){
         this.deptId = deptId;
     }

     public Long getDeptId(){
         return deptId;
     }

     public void setCgroup(String cgroup){
         this.cgroup = cgroup;
     }

     public String getCgroup(){
         return cgroup;
     }

     public void setPlandate(Date plandate){
         this.plandate = plandate;
     }

     public Date getPlandate(){
         return plandate;
     }

     public void setPlanpos(Long planpos){
         this.planpos = planpos;
     }

     public Long getPlanpos(){
         return planpos;
     }

    public Time getPlantimestart() {
        return plantimestart;
    }

    public void setPlantimestart(Time plantimestart) {
        this.plantimestart = plantimestart;
    }

    public Time getPlantimeend() {
        return plantimeend;
    }

    public void setPlantimeend(Time plantimeend) {
        this.plantimeend = plantimeend;
    }

    public void setPlanqty(Double planqty){
         this.planqty = planqty;
     }

     public Double getPlanqty(){
         return planqty;
     }

     }
