package yj.core.dftdtl.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import javax.persistence.Table;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
@ExtensionAttribute(disable=true)
@Table(name = "sap_dftdtl")
public class Dftdtl extends BaseDTO {
     @Id
     @GeneratedValue
      private String werks; //工厂

     @NotEmpty
      private String matnr; //物料编号

     @NotEmpty
      private String tlevelcode; //二级缺陷代码

      private String ztext; //二级缺陷短文本

      private String code; //缺陷代码


     public void setWerks(String werks){
         this.werks = werks;
     }

     public String getWerks(){
         return werks;
     }

     public void setMatnr(String matnr){
         this.matnr = matnr;
     }

     public String getMatnr(){
         return matnr;
     }

     public void setTlevelcode(String tlevelcode){
         this.tlevelcode = tlevelcode;
     }

     public String getTlevelcode(){
         return tlevelcode;
     }

    public String getZtext() {
        return ztext;
    }

    public void setZtext(String ztext) {
        this.ztext = ztext;
    }

    public void setCode(String code){
         this.code = code;
     }

     public String getCode(){
         return code;
     }

     }
