
package yj.core.webservice.sender;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_PP001_Sender_SyncService", targetNamespace = "http://www.cq-yj.com/HAP/PP001/Sender", wsdlLocation = "core/src/main/resources/wsdl.xml")
public class SIPP001SenderSyncService extends Service
{
    public final static URL WSDL_LOCATION;
    public final static WebServiceException SIPP001SENDERSYNCSERVICE_EXCEPTION;
    public final static QName SIPP001SENDERSYNCSERVICE_QNAME = new QName("http://www.cq-yj.com/HAP/PP001/Sender", "SI_PP001_Sender_SyncService");

    static {

        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("core/src/main/resources/wsdl.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSDL_LOCATION = url;
        SIPP001SENDERSYNCSERVICE_EXCEPTION = e;
    }

    public SIPP001SenderSyncService() {
        super(__getWsdlLocation(), SIPP001SENDERSYNCSERVICE_QNAME);
    }

    public SIPP001SenderSyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIPP001SENDERSYNCSERVICE_QNAME, features);
    }

    public SIPP001SenderSyncService(URL wsdlLocation) {
        super(wsdlLocation, SIPP001SENDERSYNCSERVICE_QNAME);
    }

    public SIPP001SenderSyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIPP001SENDERSYNCSERVICE_QNAME, features);
    }

    public SIPP001SenderSyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIPP001SenderSyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIPP001SenderSync
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPP001SenderSync getHTTPPort() {
        return super.getPort(new QName("http://www.cq-yj.com/HAP/PP001/Sender", "HTTP_Port"), SIPP001SenderSync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPP001SenderSync
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPP001SenderSync getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cq-yj.com/HAP/PP001/Sender", "HTTP_Port"), SIPP001SenderSync.class, features);
    }

    /**
     * 
     * @return
     *     returns SIPP001SenderSync
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPP001SenderSync getHTTPSPort() {
        return super.getPort(new QName("http://www.cq-yj.com/HAP/PP001/Sender", "HTTPS_Port"), SIPP001SenderSync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPP001SenderSync
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPP001SenderSync getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cq-yj.com/HAP/PP001/Sender", "HTTPS_Port"), SIPP001SenderSync.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIPP001SENDERSYNCSERVICE_EXCEPTION!= null) {
            throw SIPP001SENDERSYNCSERVICE_EXCEPTION;
        }
        return WSDL_LOCATION;
    }

}
